---
- name: Prepare machine
  hosts: all
  pre_tasks:
    - name: Run apt update cache and apt upgrade
      apt:
        upgrade: 'yes'
        update_cache: true
        cache_valid_time: 3600
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
  tasks:
    - name: 'UFW - Allow HTTP on port {{ http_port }}'
      ufw:
        rule: allow
        port: '{{ http_port }}'
        proto: tcp

- name: Deploy app
  hosts: all
  become: true
  tasks:
    - name: Create and start redmine
      community.docker.docker_container:
        name: app
        image: redmine:4.2.1
        state: started
        restart: yes
        ports:
          - '{{ http_port }}:3000'
        env:
          REDMINE_DB_POSTGRES: '{{ pg_host }}'
          REDMINE_DB_PORT: '{{ pg_port }}'
          REDMINE_DB_USERNAME: '{{ pg_user }}'
          REDMINE_DB_PASSWORD: '{{ pg_password }}'
          REDMINE_DB_DATABASE: '{{ pg_database }}'
          REDMINE_SECRET_KEY_BASE: 'true'

- name: Install and run Datadog agent
  hosts: webservers
  vars:
    datadog_site: 'datadoghq.eu'
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Application health check status
            url: 'http://localhost:{{ http_port }}'
            timeout: 5
  tasks:
    - name: Install and run datadog agent
      include_role:
        name: datadog.datadog
