---
- name: Prepare host machine
  hosts: all
  roles:
    - name: geerlingguy.pip
    - name: datadog.datadog
  tasks:
    - name: Create .env file with secrets
      ansible.builtin.template:
        src: ./templates/environment.j2
        dest: /root/.env

    - name: Create and start redmine
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: app
        image: redmine:4.2.1
        state: started
        restart: true
        published_ports:
          - '80:3000'
        env_file: /root/.env
